use_frameworks!

target 'CardinalKit_Example' do
  pod 'CardinalKit', :path => '../'
  
  # CK Sample Pods
  pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'master'
  pod 'Granola', :git => 'https://github.com/CardinalKit/Granola.git', :branch => 'main'
  
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  
  pod 'MapboxMaps', '10.1.0'

end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end
